# Copyright (C) 2023 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build & Release APK

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  apk:
    name: Build unsigned release APK
      #if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./odroidCCTV

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Build project
        run: bash ./gradlew -Pci --no-parallel --stacktrace assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: odroidCCTV/app/build/outputs/apk/release/app-release-unsigned.apk

  signing:
    name: Sign APK
    needs: apk
    runs-on: ubuntu-latest

    steps:
      - name: Download APK from build
        uses: actions/download-artifact@v1
        with:
          name: apk

      - name: Signk APK
        id: sign_apk
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: apk
          signingKeyBase64: ${{ secrets.ANDROID_SIGN_KEY }}
          alias: ${{ secrets.ANDROID_SIGN_ALIGN }}
          keyStorePassword: ${{ secrets.ANDROID_SIGN_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_SIGN_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.2"

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: signed_apk
          path: ${{ steps.sign_apk.outputs.signedReleaseFile }}

  release:
    name: Release APK
    needs: signing
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - name: Download APK from signing
        uses: actions/download-artifact@v1
        with:
          name: signed_apk

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}

      - name: Upload APK to Release
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: signed_apk/app-release-unsigned-signed.apk
          asset_name: OdroidCCTV.apk
          asset_content_type: application/zip
