name: Build & Publish Release APK
on:
  push:
    tags:
      - 'v*'
    jobs:
      apk:
        name: Generate APK
        runs-on: ubuntu-latest

        step:
          - name: checkout code
            uses: actions/checkout@v2
          - name: set up JDK 1.8
            uses: actions/setup-java@v1
            with:
              java-version: 1.8
          - name: Build with Gradle
            run: bash odroidCCTV/gradlew assembleDebug --stacktrace
          - name: Upload APK
            uses: actions/upload-artifact@v1
            with:
              name: app
              path: odroidCCTV/app/build/outputs/apk/debug
